#pragma once

enum eDirection { STOP, UP, LEFT, DOWN, RIGHT };
enum kindOfCell {IMPASSABLE, SIMPLEPASSABLE, CELL_KEY, CELL_DOOR, TRAPLOSEKEY, HEAL, TRAPDAMAGE, MAPCHANGE};
enum logLevel {WARN, INFO, TRACE, ALL};
enum typesLogMethods {NOTLOG, CONSOLE_LOG, FILE_LOG, CONSOLE_AND_FILE_LOG};